import type { CountryConfig } from "./countries";

export const ZOE_COUNTRY_CONFIG: CountryConfig = {
  code: "IL",
  locale: "he",
  dir: "rtl",
  countrySuffix: ", Israel",
  cities: [
    "Tel Aviv",
    "Jerusalem",
    "Haifa",
    "Beer Sheva",
    "Netanya",
    "Herzliya",
    "Ramat Gan",
    "Eilat",
    "Rishon LeZion",
    "Petah Tikva",
    "Ashdod",
    "Rehovot",
    "Kfar Saba",
    "Ra'anana",
    "Holon",
    "Bnei Brak",
    "Bat Yam",
    "Ashkelon",
    "Modiin",
    "Nahariya",
    "Acre",
    "Tiberias",
    "Nazareth",
    "Lod",
    "Ramla",
    "Kiryat Ata",
    "Kiryat Gat",
    "Kiryat Motzkin",
    "Kiryat Yam",
    "Kiryat Bialik",
    "Kiryat Shmona",
    "Or Yehuda",
    "Rosh HaAyin",
    "Hod HaSharon",
    "Givatayim",
    "Yokneam",
    "Afula",
    "Beit Shemesh",
    "Dimona",
    "Arad",
    "Sderot",
    "Ofakim",
    "Yavne",
    "Nesher",
    "Tirat Carmel",
    "Hadera",
    "Zichron Yaakov",
    "Caesarea",
    "Migdal HaEmek",
    "Carmiel",
  ],
  queryTemplates: [
    "pilates studios in {city}{suffix}",
    "yoga studios in {city}{suffix}",
    "hair salons in {city}{suffix}",
    "beauty clinics in {city}{suffix}",
    "personal trainers in {city}{suffix}",
    "restaurants in {city}{suffix}",
    "cafes in {city}{suffix}",
    "bars in {city}{suffix}",
    "boutique bakeries in {city}{suffix}",
    "escape rooms in {city}{suffix}",
    "bowling alleys in {city}{suffix}",
    "event venues in {city}{suffix}",
    "wedding photographers in {city}{suffix}",
    "DJs in {city}{suffix}",
    "bridal dress designers in {city}{suffix}",
    "architects in {city}{suffix}",
    "interior designers in {city}{suffix}",
    "boutique law firms in {city}{suffix}",
    "acupuncture clinics in {city}{suffix}",
    "business consultants in {city}{suffix}",
  ],
  citiesPerRun: 1,
  emailSender: "Zoe <zoe@bottie.ai>",
  emailReplyTo: "zoedotann@gmail.com",
  needsTranslation: true,
};
