import type { CountryConfig } from "./countries";

export const ZOE_COUNTRY_CONFIG: CountryConfig = {
  code: "IL",
  locale: "he",
  dir: "rtl",
  countrySuffix: ", Israel",
  cities: [
    "Tel Aviv",
    "Jerusalem",
    "Haifa",
    "Beer Sheva",
    "Netanya",
    "Herzliya",
    "Ramat Gan",
    "Eilat",
    "Rishon LeZion",
    "Petah Tikva",
    "Ashdod",
    "Rehovot",
    "Kfar Saba",
    "Ra'anana",
    "Holon",
    "Bnei Brak",
    "Bat Yam",
    "Ashkelon",
    "Modiin",
    "Nahariya",
    "Acre",
    "Tiberias",
    "Lod",
    "Ramla",
    "Kiryat Ata",
    "Kiryat Gat",
    "Kiryat Motzkin",
    "Kiryat Yam",
    "Kiryat Bialik",
    "Kiryat Shmona",
    "Or Yehuda",
    "Rosh HaAyin",
    "Hod HaSharon",
    "Givatayim",
    "Yokneam",
    "Afula",
    "Beit Shemesh",
    "Dimona",
    "Arad",
    "Sderot",
    "Ofakim",
    "Yavne",
    "Nesher",
    "Tirat Carmel",
    "Hadera",
    "Zichron Yaakov",
    "Caesarea",
    "Migdal HaEmek",
    "Carmiel",
    "Kiryat Ono",
    "Ness Ziona",
    "Mevaseret Zion",
    "Shoham",
    "Ganey Tikva",
    "Tel Mond",
    "Even Yehuda",
    "Kadima-Tzoran",
    "Pardes Hanna-Karkur",
    "Binyamina",
    "Kiryat Tivon",
    "Savyon",
    "Safed",
    "Nof HaGalil",
    "Harish",
    "Gedera",
    "Ma'ale Adumim",
    "Netivot",
    "Kiryat Malakhi",
    "Ramat HaSharon",
    "Yehud-Monosson",
    "Givat Shmuel",
    "Omer",
    "Meitar",
    "Lehavim",
    "Kfar Shmaryahu",
    "Kfar Tavor",
    "Rosh Pina",
    "Mazkeret Batya",
    "Gan Yavne",
    "Tzur Hadassah",
    "Or Akiva",
    "Ma'alot-Tarshiha",
    "Beit She'an",
    "Yeruham",
    "Mitzpe Ramon",
    "Kfar Vradim",
    "Efrat",
    "Givat Ze'ev",
    "Be'er Ya'akov",
    "Kiryat Arba",
    "Ariel",
    "Elkana",
    "Modi'in Illit",
    "Beitar Illit",
    "Kochav Yair",
    "Alfei Menashe",
    "Eli",
    "Ofra",
    "Talmon",
    "Hashmonaim",
    "Elad",
    "Atlit",
    "Yokne'am Illit",
    "Hatzor HaGlilit",
    "Kfar Yona",
    "Beit Dagan",
    "Azor",
    "Givat Olga",
    "Pardesiya",
    "Beit Aryeh-Ofarim",
    "Geva Binyamin",
    "Karnei Shomron",
    "Kedumim",
    "Beit El",
    "Shilo",
    "Tekoa",
    "Alon Shvut",
    "Ma'ale Mikhmas",
    "Mitzpe Yericho",
    "Kfar Adumim",
    "Yad Binyamin",
    "Bnei Re'em",
    "Even Shmuel",
    "Ramat Beit Shemesh",
    "Bnei Ayish",
  ],
  queryTemplates: [
    "pilates studios in {city}{suffix}",
    "yoga studios in {city}{suffix}",
    "hair salons in {city}{suffix}",
    "beauty clinics in {city}{suffix}",
    "personal trainers in {city}{suffix}",
    "restaurants in {city}{suffix}",
    "cafes in {city}{suffix}",
    "bars in {city}{suffix}",
    "boutique bakeries in {city}{suffix}",
    "escape rooms in {city}{suffix}",
    "bowling alleys in {city}{suffix}",
    "event venues in {city}{suffix}",
    "wedding photographers in {city}{suffix}",
    "DJs in {city}{suffix}",
    "bridal dress designers in {city}{suffix}",
    "architects in {city}{suffix}",
    "interior designers in {city}{suffix}",
    "boutique law firms in {city}{suffix}",
    "acupuncture clinics in {city}{suffix}",
    "business consultants in {city}{suffix}",
    "dental clinics in {city}{suffix}",
    "nail salons in {city}{suffix}",
    "barbershops in {city}{suffix}",
    "tattoo studios in {city}{suffix}",
    "spas in {city}{suffix}",
    "med spas in {city}{suffix}",
    "massage therapists in {city}{suffix}",
    "nutritionists in {city}{suffix}",
    "psychologists in {city}{suffix}",
    "photographers in {city}{suffix}",
    "florists in {city}{suffix}",
    "jewelry designers in {city}{suffix}",
    "fashion boutiques in {city}{suffix}",
    "concept stores in {city}{suffix}",
    "specialty coffee shops in {city}{suffix}",
    "wine bars in {city}{suffix}",
    "cocktail bars in {city}{suffix}",
    "catering services in {city}{suffix}",
    "dance studios in {city}{suffix}",
    "makeup artists in {city}{suffix}",
    "real estate agencies in {city}{suffix}",
    "travel agencies in {city}{suffix}",
    "kids activity centers in {city}{suffix}",
    "music schools in {city}{suffix}",
    "veterinary clinics in {city}{suffix}",
    "chiropractors in {city}{suffix}",
    "physiotherapy clinics in {city}{suffix}",
    "speech therapists in {city}{suffix}",
    "occupational therapists in {city}{suffix}",
    "optometrists in {city}{suffix}",
    "aesthetic clinics in {city}{suffix}",
    "lash studios in {city}{suffix}",
    "crossfit gyms in {city}{suffix}",
    "boxing gyms in {city}{suffix}",
    "martial arts studios in {city}{suffix}",
    "climbing gyms in {city}{suffix}",
    "sushi restaurants in {city}{suffix}",
    "ice cream shops in {city}{suffix}",
    "chocolatiers in {city}{suffix}",
    "patisseries in {city}{suffix}",
    "wineries in {city}{suffix}",
    "breweries in {city}{suffix}",
    "bookstores in {city}{suffix}",
    "art galleries in {city}{suffix}",
    "home decor stores in {city}{suffix}",
    "plant nurseries in {city}{suffix}",
    "bike shops in {city}{suffix}",
    "co-working spaces in {city}{suffix}",
    "marketing agencies in {city}{suffix}",
    "web design studios in {city}{suffix}",
    "video production studios in {city}{suffix}",
    "accountants in {city}{suffix}",
    "tour guides in {city}{suffix}",
    "boutique hotels in {city}{suffix}",
    "bed and breakfasts in {city}{suffix}",
    "tutoring centers in {city}{suffix}",
    "driving schools in {city}{suffix}",
    "language schools in {city}{suffix}",
  ],
  citiesPerRun: 1,
  emailSender: "Zoe <zoe@zoedotan.com>",
  emailReplyTo: "zoedotann@gmail.com",
  needsTranslation: true,
};
